### ISSUE TITLE
Amenu not Launching 

### ISSUE THREAD

**Issue by sadiemay711** [salman-abedin/amenu#1]
Hey, I really like this project, and after following the instructions, I can't get it to launch. I'm running dwm and I added the lines to make amenu floating and double checked that the script was using st. I have both fzf and tail installed. When run, it gives no other output. I also tried it with termite + xterm and got the same result. Any ideas for what I could be doing wrong?

**Comment by salman-abedin** [comment]
Glad to hear you like the project. As far as your issues are concerned, try the following commands on your shell and let me know whether you got the expected results or not.
```sh
# Launches a floating terminal instance
st -c amenu
# Launches a floating instance with fzf
st -c amenu -e "$SHELL" -c "fzf" 
```

For future reference, you can knock me at matrix with the handle @greylotus.

**Comment by sadiemay711** [comment]
The second command works but it's the exact same whether or not I have the "-c amenu" part or not. I think it could be something to do with floating window rules in dwm, but I'm not sure. I don't mean to sound pessimistic, but I think I'll just give up and go back to my patched dmenu. Your setup does look pretty sweet with it

**Comment by salman-abedin** [comment]
I think I figured it out. I was using one of my environment variable(i.e. $TERMINAL) to define the terminal emulator.  
My bad! 😅  
Pull down the changes and give it another shot.  
And also, make sure you've got the following line on your dwm config.
```c
static const Rule rules[] = {
    //...
    {"amenu", 0, 0, 0, 1, -1},
    //...
};

```

**Comment by sadiemay711** [comment]
Woah! Thanks, I have it launching now. Just gotta configure the dwm part. I've got that section in my config.h, but I have mine patched with some things I probably don't need, so it looks like this:
```
static const Rule rules[] = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
	/* class      instance    title       tags mask     isfloating   monitor  scratch key  float x,y,w,h         floatborderpx*/
	{ "Gimp",     NULL,       NULL,       0,            1,           -1,        0,            50,50,500,500,        5 },
	{ "Firefox",  NULL,       NULL,       1 << 8,       0,           -1,        0,            50,50,500,500,        5 },
	{ "St",      NULL,     NULL,           0,         0,          1,           0,        -1,	50,50,500,500, 5 },
	{ "amenu",  NULL, NULL,  0,         0,          0,           1,        -1,	50,50,500,500, 5 },
 	{ NULL,      NULL,     "Event Tester", 0,         0,          0,           0,        -1 }, /* xev */
};
```
Which section should "amenu" be in? Is that a stupid question? I looked at your dwm config and now I'm just more confused 0_0

**Comment by sadiemay711** [comment]
It's all good! I got it figured out now. I just removed some patches I wasn't using and then did just as you said. Works like a charm! Thanks for this project! I think I'm gonna make my various dmenu scripts try and work in it, so I can have a consistent theme throughout.

**Comment by salman-abedin** [comment]
Great!   
FYI, Try using an environment variable on your scripts. They are really convenient for swapping programs back and forth.

**Comment by sadiemay711** [comment]
Oh! Thanks, that's a really great idea. Is there any way to change the monitor it spawns on? I know that it's the primary one, but when I'm on the secondary monitor, I have to shift focus to the window because it's on the other display. Could it possibly be a variable in the script or even have dwm to spawn it with the monitor in focus?
